name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Build :
    name: Build
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: latest
        run: |
          docker build -t myrepo/twemproxy .
#          docker push $REGISTRY:$IMAGE_TAG
#          echo "::set-output name=image::$REGISTRY:$IMAGE_TAG"
          
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}          
